// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbccposnamjykgdoqrlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiY2Nwb3NuYW1qeWtnZG9xcmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjE1MzgsImV4cCI6MjA3MTU5NzUzOH0.N2BSW3WzQzHD6oGM8XzUY-TithHap2BOt6HI2eeQo9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});